name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      # - name: Setup Ruby for Asciidoctor
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.1'

      # - name: Install Asciidoctor and Diagram tools
      #   run: |
      #     gem install asciidoctor asciidoctor-pdf asciidoctor-diagram
      #     sudo apt-get update
      #     sudo apt-get install -y default-jre graphviz

      # - name: Download PlantUML jar
      #   run: |
      #     mkdir -p $HOME/plantuml
      #     curl -L -o $HOME/plantuml/plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
      #     echo "DIAGRAM_PLANTUML_CLASSPATH=$HOME/plantuml/plantuml.jar" >> $GITHUB_ENV

      # - name: Build Documentation
      #   run: |
      #     mkdir -p build/docs
      #     asciidoctor -r asciidoctor-diagram docs/index.adoc -o build/docs/index.html
      #     asciidoctor-pdf -r asciidoctor-diagram docs/index.adoc -o build/docs/crosspay.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KIRA }}
          publish_dir: ./build
