name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        

      - name: Build project
        run: npm run build

      # === ДОБАВЛЕННЫЕ СТРОКИ ДЛЯ ДОКУМЕНТАЦИИ ===
      - name: Setup Ruby for Asciidoctor
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Install Asciidoctor
        run: gem install asciidoctor asciidoctor-pdf
      
      - name: Install Asciidoctor and PlantUML
        run: |
          gem install asciidoctor asciidoctor-pdf
          sudo apt-get update && sudo apt-get install -y plantuml
          # Или для Mac в GitHub Actions:
          # brew install plantuml
      
      - name: Generate PlantUML diagrams
        run: |
          mkdir -p build/docs/images
          plantuml -tpng plantuml/architecture.puml -o build/docs/images/
          plantuml -tsvg plantuml/architecture.puml -o build/docs/images/
      
      # === КОНЕЦ ДОБАВЛЕННЫХ СТРОК ===

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KIRA }}
          publish_dir: ./build
